name: Desafio1

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0
            
   
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./repo
          push: true
          tags: gabogrobier/desafio-1:1.0.0

